### ISSUE TITLE
Remove serialize from resources?

### ISSUE THREAD

**Issue by kbacha** [kbacha/stellar-sdk#128]
### Expected Behavior
The resources reflect the data returned from the horizon API and it makes sense for them to deserialize the JSON coming from horizon. However, there is no need for them to serialize back to that json and some are not implemented to do that.

Since Horizon does not accept these JSON as any POST commands, I suggest that we remove serialize implementations and leave everything as strictly deserialize. This simplifies the behavior and doesn't add to confusion latter when in use in another application.

### Actual Behavior
A mixed bag of resources implement serialize.

**Comment by correlator** [comment]
Good question.  In our .2 release we will be building transactions out of operations.  Those operations will have a ton of resources and we will also have to serialize them.  Given that this is coming in the future and that we don't know the exact behavior we would want at this point I'm happy to nuke it for the time being.

**Comment by kbacha** [comment]
Cool, I think I'll leave ones that are like newtypes since those are useful in other structs outside the resources themselves.
