### ISSUE TITLE
Add All Ledgers Endpoint to CLI

### ISSUE THREAD

**Issue by correlator** [kbacha/stellar-sdk#159]
### Expected Behavior
```
stellar ledgers 
```
This should also take cursor, order, and page-limit as arguments.

### Ledger details to display
```
id
hash
```
https://www.stellar.org/developers/horizon/reference/endpoints/ledgers-all.html

**Comment by robertDurst** [comment]
Interested in taking a stab at this -- aka since I am not an official member of this project, this is my way of saying "ASSIGN TO ME"

Also, I think it should stay this way. Will look better for when y'all apply for the next Stellar Build Challenge 😉

**Comment by correlator** [comment]
@robertDurst you can feel free to grab any ticket that hasn't been previously assigned.  But I'm happy to throw you on this one.  You are 100% a crucial contributor to the project!

**Comment by robertDurst** [comment]
@correlator id == hash 😆

**Comment by robertDurst** [comment]
Here is what I propose:
```
hash
sequence
transaction_count
operation_count
closed_at
```

**Comment by robertDurst** [comment]
Here is a preview:

<img width="526" alt="screen shot 2018-04-17 at 10 33 19 pm" src="https://user-images.githubusercontent.com/16689974/38913389-5ca91eac-428f-11e8-8830-c1cbd5ee2b00.png">
