### ISSUE TITLE
Add All Payments Endpoint to CLI

### ISSUE THREAD

**Issue by correlator** [kbacha/stellar-sdk#167]
### Expected Behavior
```
stellar payments all
```
This should also take cursor, order, and page-limit as arguments.

### Payment details to display
```
id
to
from
asset
amount
```
https://www.stellar.org/developers/horizon/reference/endpoints/payments-all.html

**Comment by robertDurst** [comment]
Interested -- Self Assigning to me :)

**Comment by robertDurst** [comment]
Payments consist of many different ops. Haven't determined them all yet, but so far:

* payment
* create account
* payment path
