### ISSUE TITLE
CLI network option/flag ordering confusion

### ISSUE THREAD

**Issue by robertDurst** [kbacha/stellar-sdk#186]
### Expected Behavior
I expected to be able to specify network anywhere as part of cli.
```
stellar payments --pub-net all
```
or
```
stellar payments all --pub-net
```

### Actual Behavior
Requires network flag after stellar keyword.
```
stellar --pub-net payments all
```

### Steps to reproduce
n/a

### Conclusion
This is not necessarily a bug or an issue. For some reason it was not immediately obvious that this option/flag should come right after the stellar keyword -- wanted to raise this concern just in case other people felt the same way or may experience this later on.

**Comment by kbacha** [comment]
I believe this may be how the parsing of the CLI is intended to behave. The network flag applies to the global namespace (`stellar`) so it must follow that command. Each of the lower sub-commands behave as distinct entities and have their own distinct options. If the option could "float" between commands, then it could also collide with sub-commands and create confusion around usage.

I would say that this is likely working as intended. And example would be how `docker` and `docker-compose` have various levels of commands and where the flags go can depend on which command you are modifying. In this case you are modifying the connection to stellar, that applies to all commands, so it's at the top level.

**Comment by robertDurst** [comment]
Awesome, just some confusion on my part.
