### ISSUE TITLE
Remove FromStr for AssetIdentifier from CLI

### ISSUE THREAD

**Issue by robertDurst** [kbacha/stellar-sdk#223]
As part of #215 I ported `FromStr` for `AssetIdentifier` to Client. Since it lives in client, it doesn't also have to live in CLI.

Ref: https://github.com/kbacha/stellar-sdk/blob/master/cli/src/asset_identifier.rs#L4

However, as you may notice this is in fact the only method here... therefore this mod could probably be totally removed.

**Comment by robertDurst** [comment]
@kbacha @alexanderreiff @correlator  the CLI is technically "full feature" as of #215 however you think this is necessary for v1 CLI launch?

Some context... I ported `FromStr` into the client and did not delete it from CLI, so it now lives in two places.

**Comment by robertDurst** [comment]
closed via #224 @kbacha @correlator @alexanderreiff CLI is done!

**Comment by correlator** [comment]
Time for a new dot release on crates @kbacha @robertDurst ?
