### ISSUE TITLE
Doc Test Suite Fails - Orderbook liabilities and Bumpseq Update (v10 of stellar-core)

### ISSUE THREAD

**Issue by robertDurst** [kbacha/stellar-sdk#227]
### Expected Behavior
Tests fail.

### Actual Behavior
Tests succeed.

### Steps to reproduce
`cargo test`

### Reason for fail
Most likely: protocol v10 core/ 0.14.0 Horizon changes

### Failing tests

* `test src/endpoint/payment.rs - endpoint::payment::FindPath (line 131)`
* `test src/endpoint/trade.rs - endpoint::trade::Aggregations (line 342)`
* `test src/endpoint/account.rs - endpoint::account::Offers (line 900)`

**Comment by kbacha** [comment]
I think this is fixed but there's still some issues with the find path endpoint in horizon. That's not fixable inside the sdk.
