### ISSUE TITLE
[endpoint] All ledgers

### ISSUE THREAD

**Issue by kbacha** [kbacha/stellar-sdk#57]
This endpoint represents all ledgers.

https://www.stellar.org/developers/horizon/reference/endpoints/ledgers-all.html

**Comment by robertDurst** [comment]
Hey, I am interested in taking a stab at this. I am assuming an implementation of this would be very similar to [All Assets](https://github.com/kbacha/stellar-sdk/blob/master/client/src/endpoint/asset.rs) and thus I could use All Assets as a guide?

**Comment by kbacha** [comment]
Yup, I think you can.
