### ISSUE TITLE
[endpoint] Ledger Details

### ISSUE THREAD

**Issue by kbacha** [kbacha/stellar-sdk#59]
The ledger details endpoint provides information on a single ledger.

https://www.stellar.org/developers/horizon/reference/endpoints/ledgers-single.html

**Comment by robertDurst** [comment]
Once I get #67 all squared away, this seems like a natural follow up

**Comment by robertDurst** [comment]
Going off of #69 should I implement the Details such that we have:

```ledger::Details```

Just like we have:

```ledger::All```

**Comment by kbacha** [comment]
Yessir!
