### ISSUE TITLE
[endpoint] Operations for ledger

### ISSUE THREAD

**Issue by kbacha** [kbacha/stellar-sdk#64]
This endpoint returns all operations that occurred in a given ledger.

This should go into the ledger module

https://www.stellar.org/developers/horizon/reference/endpoints/operations-for-ledger.html

**Comment by robertDurst** [comment]
Interested in this following #84. Keep the ledger module moment going 💯 

I am assuming this is ```ledgers::Operations```

**Comment by kbacha** [comment]
@robertDurst you may want to wait on @correlator I think he found an issue with type compatibility with Operations and the endpoint he's working on.

**Comment by correlator** [comment]
Yes please hold off on anything having to do with operations or effects.  I'm going to clean those things up over the weekend.

**Comment by robertDurst** [comment]
Sounds good, I'll hold off @correlator

**Comment by correlator** [comment]
@robertDurst you still want this one?

**Comment by robertDurst** [comment]
@correlator Working on #89 right now and probably won't have it finished until tonight so this one is up for grabs!
