### ISSUE TITLE
Decide on strategy to fix horizon rate limits breaking tests

### ISSUE THREAD

**Issue by correlator** [kbacha/stellar-sdk#80]
Our client tests actually ping the horizon test server.  We now have enough tests that we are being rated limited and therefore have blinking tests.

We can set up our own horizon server for testing, we can configure Travis to ignore all external calls, or do something else.  

The output of this issue should be an issue

**Comment by kbacha** [comment]
@correlator How's this? https://github.com/kbacha/stellar-sdk/issues/81
