### ISSUE TITLE
[endpoint] All transactions

### ISSUE THREAD

**Issue by kbacha** [kbacha/stellar-sdk#90]
This endpoint represents all validated transactions. This endpoint can also be used in streaming mode. This makes it possible to use it to listen for new transactions as they get made in the Stellar network.

```rust
use stellar_client::endpoint::transaction::All;
```

https://www.stellar.org/developers/horizon/reference/endpoints/transactions-all.html

**Comment by bringking** [comment]
@kbacha I would like to take a stab at this over the weekend!
