### ISSUE TITLE
[endpoint] Transactions for account

### ISSUE THREAD

**Issue by kbacha** [kbacha/stellar-sdk#91]
This endpoint represents all transactions that affected a given account. This endpoint can also be used in streaming mode so it is possible to use it to listen for new transactions as that affect a given account as they get made in the Stellar network

```rust
use stellar_client::endpoint::account::Transactions;
```

https://www.stellar.org/developers/horizon/reference/endpoints/transactions-for-account.html

**Comment by bringking** [comment]
@kbacha I want to take stab at this one too!
